import { getProfile } from "@/lib/services/users";
import { ThemeProvider } from "@/providers/theme-provider";
import { UrqlProvider } from "@/providers/urql";
import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ui/toast";
import { PageLayout } from "@/components/custom-components/page-layout";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userData = await getProfile();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${interSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UrqlProvider>
            <ToastProvider position="top-center">
              <PageLayout
                userData={{
                  email: userData?.email ?? "",
                  fullName: userData?.fullName ?? "",
                  profilePicture: userData?.profilePicture ?? "",
                  role: userData?.role?.name ?? "",
                }}
              >
                {children}
              </PageLayout>
            </ToastProvider>
          </UrqlProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
